#!/usr/bin/env sh

get_screen() {
  hyprctl monitors \
    | grep "Monitor" -A 1 \
    | grep -v -e "Monitor" -e "--" \
    | cut -d $'\t' -f 2 \
    | cut -d '@' -f 1
}

get_screen_width() {
  get_screen \
    | cut -d 'x' -f 1 \
    | awk '{s+=$1} END {print s}'
}

get_screen_height() {
  get_screen \
    | cut -d 'x' -f 2 \
    | grep -m1 ""
}

get_pose() {
  hyprctl monitors \
    | grep "Monitor" -A 1 \
    | grep -v -e "Monitor" -e "--" \
    | cut -d $'\t' -f 2 \
    | cut -d '@' -f 2 \
    | cut -d ' ' -f 3
}

get_pose_width() {
  get_pose \
    | cut -d 'x' -f 1 \
    | grep -m1 ""
}

get_pose_height() {
  get_pose \
    | cut -d 'x' -f 2 \
    | grep -m1 ""
}

SCREEN_WIDTH=$(
  get_screen \
    | cut -d 'x' -f 1 \
    | grep -m1 ""
)
SCREEN_HEIGHT=$(get_screen_height)

hyprctl dispatch resizeactive exact $((SCREEN_WIDTH - 25)) $((SCREEN_HEIGHT - 67))
hyprctl dispatch togglefloating
hyprctl dispatch resizeactive exact $(get_screen_width) $(get_screen_height)
hyprctl dispatch moveactive exact $(get_pose_width) $(get_pose_height)

GLOBAL_FULLSCREEN_APP_EXIST=$(
  hyprctl clients \
    | grep "floating: 1" -B 2 \
    | grep "size: $(get_screen_width),$(get_screen_height)"
)

if [ "${GLOBAL_FULLSCREEN_APP_EXIST}x" != "x" ]; then
  pkill -f waybar
  while [ "${GLOBAL_FULLSCREEN_APP_EXIST}x" != "x" ]; do
    GLOBAL_FULLSCREEN_APP_EXIST=$(
      hyprctl clients \
        | grep "floating: 1" -B 2 \
        | grep "size: $(get_screen_width),$(get_screen_height)"
    )
    sleep 1
  done
  WAYBAR_EXTST=$(
    ps aux \
      | grep 'waybar' \
      | grep -v 'grep'
  )

  [ "${WAYBAR_EXTST}" == "" ] && \
    waybar &
fi
