#! /usr/bin/env bash

no() {
  yes | sed 's/y/n/g'
}

lvim_install() {
  no | LV_BRANCH='release-1.3/neovim-0.9' bash <( \
    curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh \
  )
}

[ ! -f "${HOME}/.local/bin/lvim" ] \
  && lvim_install

FolderIdeCommand() {
  lvim -c "NvimTreeToggle"
}

FileIdeCommand() {
  lvim ${1}
}

ideCommand="FileIdeCommand ${1}"
if [ -d "${1}" ] 2> /dev/null; then
  cd ${1}
  ideCommand="FolderIdeCommand"
fi
if [ "${1}x" == "x" ] 2> /dev/null; then
  ideCommand="FolderIdeCommand"
fi

$ideCommand
