#! /usr/bin/env bash

FolderIdeCommand() {
  lvim -c "NvimTreeToggle"
}

FileIdeCommand() {
  lvim ${1}
}

ideCommand="FileIdeCommand ${1}"
if [ -d "${1}" ] 2> /dev/null; then
  cd ${1}
  ideCommand="FolderIdeCommand"
fi
if [ "${1}x" == "x" ] 2> /dev/null; then
  ideCommand="FolderIdeCommand"
fi

$ideCommand
