#!/usr/bin/env sh

mkdir -p ~/.local/share/fonts/store

FONTS=$(
  find /nix/store/ | \
    grep "/share/fonts/" | \
    grep  -e ".ttf" -e ".otf" | \
    grep -v "ttf'" | grep -v "otf'"
)

for FONT in ${FONTS}; do
  sudo cp -n ${FONT} \
    ~/.local/share/fonts/store/ \
    1> /dev/null 2> /dev/null
done
sudo chown -R gabriel:users ~/.local/share/fonts/store/
sudo chmod 755 -R ~/.local/share/fonts/store/
